export const STATIC_PRODUCTS = [
  {
    id: 'facewash',
    name: 'ULTRA SENSITIVE GOLD GLOW FACEWASH',
    shortName: 'FACEWASH',
    displayName: 'Gold Glow Facewash',
    subtitle: 'Ultra Sensitive Gold Glow',
    category: 'cleanse',
    tagline: 'Gentle Luxury Cleanse with Gold Glow & Herbal Care',
    price: 249,
    priceDisplay: '₹249.00',
    size: '100 ML',
    sizeDetail: '100 ml (3.38 fl oz)',
    rating: 4.8,
    image: '',
    themeColor: '#4A7C59',
    themeBg: '#EDF4ED',
    themeGradient: ['#EDF4ED', '#F5F9F5'] as [string, string],
    highlights: [
      { icon: 'leaf', label: 'Crystal clear gel with real gold flakes' },
      { icon: 'droplets', label: 'Ultra gentle sulphate-free cleansing' },
      { icon: 'sparkles', label: 'Herbal glow boosting formula' },
    ],
    benefits: [
      'Deep yet gentle cleansing',
      'Instant freshness & soft glow',
      'Helps reduce redness & irritation',
      'Hydrates and soothes skin',
      'Promotes radiant complexion',
    ],
    concerns: ['Dullness', 'Mild Redness', 'Sensitivity', 'Dehydrated Skin', 'Uneven Texture'],
    description: 'A luxurious crystal clear gel facewash infused with herbal extracts, hydrosols and real gold flakes that gently cleanses impurities while soothing sensitive skin and enhancing natural glow.',
    storyTitle: 'The Gold Glow Ritual',
    storyText: 'Infused with 24K Gold Leaf and Kumkumadi Taila, this crystal-clear gel transforms your daily cleanse into a luxurious botanical ritual. Each wash reveals softer, more radiant skin with a golden luminescence.',
    stats: [
      { value: '98%', label: 'FELT SOFTER SKIN' },
      { value: '95%', label: 'VISIBLE GLOW' },
      { value: '92%', label: 'REDUCED REDNESS' },
    ],
    featuredIngredients: [
      { name: 'Rose Hydrosol', desc: 'A gentle floral water that soothes, tones and hydrates sensitive skin while reducing redness.' },
      { name: 'Saffron Extract', desc: 'The golden spice that brightens complexion, evens skin tone and imparts a natural luminous glow.' },
      { name: '24K Gold Leaf', desc: 'Pure gold particles that boost radiance, stimulate cell renewal and add luxurious luminescence.' },
    ],
    allIngredients: ['Rose Hydrosol', 'Saffron Extract', 'Licorice Extract', 'Manjistha', 'Amla', 'Gotu Kola', 'Chamomile', 'Sandalwood', 'Lotus', 'Neem', 'Tulsi', 'Organic Honey', 'Vitamin E', 'Kumkumadi Taila', 'Gold Nano Dust', '24K Gold Leaf'],
    texture: 'Lightweight crystal clear gel with visible gold flakes',
    fragrance: 'Soft floral luxury fragrance with rose & saffron notes',
    howToUse: 'Take a small amount on wet face, gently massage in circular motion and rinse with water. Pat dry.',
    whenToUse: 'Morning & Night (twice daily)',
    suitableFor: ['All Skin Types', 'Sensitive Skin'],
    claims: ['Sulphate Free', 'Paraben Free', 'Soap Free', 'Gentle Surfactants', 'pH Balanced', 'Dermatologically Inspired'],
    shelfLife: '24 Months',
    storage: 'Store in cool & dry place. Keep away from direct sunlight.',
    safety: 'For external use only. Avoid contact with eyes. Patch test recommended.',
    reviews: [
      { text: 'Very gentle and leaves my skin soft with a beautiful natural glow. The gold flakes are such a luxurious touch.', author: 'Priya M.', rating: 5 },
      { text: 'Perfect for sensitive skin! Cleans well without any dryness or tightness.', author: 'Ananya R.', rating: 5 },
      { text: 'Light gel formula that hydrates and gives a fresh radiant look every morning.', author: 'Deepika S.', rating: 5 },
    ],
    storyImage: '',
  },
  {
    id: 'hairserum',
    name: 'ULTRA SENSITIVE SMOOTH & SHINE HAIR SERUM',
    shortName: 'HAIR SERUM',
    displayName: 'Smooth & Shine Hair Serum',
    subtitle: 'Ultra Sensitive Smooth',
    category: 'hair',
    tagline: 'Weightless Smoothness · Natural Shine · Zero Silicone Feel',
    price: 349,
    priceDisplay: '₹349.00',
    size: '30 ML',
    sizeDetail: '30 ml (1.0 fl oz)',
    rating: 4.8,
    image: '',
    themeColor: '#108cba',
    themeBg: '#E8F4FA',
    themeGradient: ['#E8F4FA', '#F0F8FC'] as [string, string],
    highlights: [
      { icon: 'droplets', label: 'Ultra-light nourishing oil blend' },
      { icon: 'leaf', label: 'Ayurvedic scalp-friendly actives' },
      { icon: 'sparkles', label: 'Smooth & shine boosting formula' },
    ],
    benefits: [
      'Adds natural shine and smoothness',
      'Helps control frizz and dryness',
      'Nourishes scalp without heaviness',
    ],
    concerns: ['Dry Hair', 'Frizz', 'Rough Texture', 'Sensitive Scalp'],
    description: 'A lightweight leave-in hair serum formulated with botanical oils and Ayurvedic extracts to smooth frizz, enhance shine and nourish scalp gently without greasy residue.',
    storyTitle: 'Weightless Botanical Perfection',
    storyText: 'A carefully crafted blend of Argan, Jojoba and Bhringraj oils combined with Ayurvedic scalp-friendly extracts. This silicone-free formula delivers weightless smoothness and natural mirror-like shine.',
    stats: [
      { value: '96%', label: 'SMOOTHER HAIR' },
      { value: '93%', label: 'REDUCED FRIZZ' },
      { value: '97%', label: 'NATURAL SHINE' },
    ],
    featuredIngredients: [
      { name: 'Argan Oil', desc: 'Liquid gold from Morocco that deeply nourishes, tames frizz and adds a brilliant, healthy shine.' },
      { name: 'Bhringraj Oil', desc: 'The king of Ayurvedic hair herbs, strengthening roots, promoting growth and restoring natural vitality.' },
      { name: 'Olive Squalane', desc: 'A lightweight botanical emollient that seals moisture, smooths cuticles and adds weightless silk.' },
    ],
    allIngredients: ['Coconut MCT Oil', 'Jojoba Oil', 'Argan Oil', 'Sweet Almond Oil', 'Bhringraj Oil', 'Hibiscus Extract', 'Licorice Extract', 'Fenugreek Extract', 'Olive Squalane', 'Vitamin E'],
    texture: 'Ultra-light, Non-sticky, Silky',
    fragrance: 'Mild natural fragrance',
    howToUse: 'Take a few drops, apply on hair lengths and ends, and gently smooth through.',
    whenToUse: 'Daily / After Wash / Styling',
    suitableFor: ['Normal Hair', 'Sensitive & Dry Hair', 'Sensitive Scalp'],
    claims: ['Silicone Free', 'Lightweight', 'Non-sticky', 'Gentle Botanical Formula'],
    shelfLife: '24 Months',
    storage: 'Store in a cool & dry place away from direct sunlight.',
    safety: 'For external use only. Avoid contact with eyes.',
    reviews: [
      { text: 'Smooth and shiny finish without any heaviness. My hair has never looked better.', author: 'Sneha K.', rating: 5 },
      { text: 'Lightweight and non-greasy, perfect for my daily routine. Love the natural fragrance.', author: 'Kavya P.', rating: 5 },
      { text: 'Perfect for sensitive scalp care and frizz control. Finally a serum that works!', author: 'Riya T.', rating: 4 },
    ],
  },
  {
    id: 'faceserum',
    name: 'ULTRA SENSITIVE GLOW & CORRECT FACE SERUM',
    shortName: 'FACE SERUM',
    displayName: 'Glow & Correct Face Serum',
    subtitle: 'Ultra Sensitive Glow & Correct',
    category: 'serum',
    tagline: 'Gentle Brightening · No Irritation · Daily Glow Boost',
    price: 449,
    priceDisplay: '₹449.00',
    size: '30 ML',
    sizeDetail: '30 ml (1.0 fl oz)',
    rating: 4.8,
    image: '',
    themeColor: '#1BA8A0',
    themeBg: '#E5F5F3',
    themeGradient: ['#E5F5F3', '#EFF9F8'] as [string, string],
    highlights: [
      { icon: 'droplets', label: 'Soothing hydrosol-based formula' },
      { icon: 'sparkles', label: 'Mild pigmentation correcting actives' },
      { icon: 'leaf', label: 'Lightweight hydration & barrier support' },
    ],
    benefits: [
      'Helps brighten and even skin tone',
      'Reduces mild pigmentation & dullness',
      'Deep hydration with calming effect',
    ],
    concerns: ['Pigmentation', 'Dull Skin', 'Sensitivity', 'Uneven Tone'],
    description: 'A gentle face serum formulated with hydrosols, botanical extracts and mild actives to brighten skin, reduce pigmentation and provide soothing hydration without irritation.',
    storyTitle: 'The Science of Gentle Brightening',
    storyText: 'Combining Alpha Arbutin with Vitamin C and Bakuchiol in a hydrosol base, this serum delivers visible brightening without the irritation. Sensitive skin finally gets the glow treatment it deserves.',
    stats: [
      { value: '94%', label: 'EVEN SKIN TONE' },
      { value: '97%', label: 'HYDRATED SKIN' },
      { value: '91%', label: 'REDUCED PIGMENTATION' },
    ],
    featuredIngredients: [
      { name: 'Alpha Arbutin', desc: 'A gentle yet effective brightening agent that reduces dark spots and evens skin tone without irritation.' },
      { name: 'Vitamin C', desc: 'A powerful antioxidant that boosts collagen, brightens complexion and protects against environmental stress.' },
      { name: 'Bakuchiol', desc: 'Nature’s retinol alternative. Smooths fine lines and improves texture without any sensitivity.' },
    ],
    allIngredients: ['Aloe Vera', 'Rose Hydrosol', 'Licorice Extract', 'Alpha Arbutin', 'Gotu Kola', 'Vitamin C', 'Panthenol', 'Sodium Hyaluronate', 'Chamomile', 'Bakuchiol'],
    texture: 'Lightweight, Gel-serum, Non-sticky',
    fragrance: 'Mild natural fragrance',
    howToUse: 'Apply 2–3 drops on clean face and gently pat until absorbed.',
    whenToUse: 'AM & PM / Daily',
    suitableFor: ['Sensitive Skin', 'Very Sensitive Skin', 'Normal Skin'],
    claims: ['No Tingling', 'No Irritation', 'Alcohol Free', 'Gentle Brightening Formula'],
    shelfLife: '24 Months',
    storage: 'Store in a cool & dry place away from direct sunlight.',
    safety: 'For external use only. Avoid contact with eyes. Patch test recommended.',
    reviews: [
      { text: 'Lightweight and soothing serum. My skin glows without any irritation at all.', author: 'Meera J.', rating: 5 },
      { text: 'Gentle glow boost that works beautifully on my sensitive skin. No redness!', author: 'Aisha N.', rating: 5 },
      { text: 'Hydrating and non-sticky feel. I can see my pigmentation fading already.', author: 'Tanvi G.', rating: 5 },
    ],
  },
  {
    id: 'nightcream',
    name: 'ULTRA SENSITIVE REPAIR NIGHT CREAM',
    shortName: 'NIGHT CREAM',
    displayName: 'Repair Night Cream',
    subtitle: 'Ultra Sensitive Repair',
    category: 'night',
    tagline: 'Low Irritation · Acne Safe · Overnight Skin Repair',
    price: 399,
    priceDisplay: '₹399.00',
    size: '30 G',
    sizeDetail: '30g / 1.0 fl oz',
    rating: 4.8,
    image: '',
    gallery: [
      '',
      '',
      '',
      '',
      '',
    ],
    video: '',
    themeColor: '#8B2252',
    themeBg: '#F6ECF0',
    themeGradient: ['#F6ECF0', '#FAF3F6'] as [string, string],
    highlights: [
      { icon: 'leaf', label: 'Botanical calming hydrosol base' },
      { icon: 'droplets', label: 'Lightweight nourishing oils' },
      { icon: 'sparkles', label: 'Active soothing & brightening complex' },
    ],
    benefits: [
      'Calms and repairs sensitive skin',
      'Provides deep overnight hydration',
      'Improves softness and natural glow',
    ],
    concerns: ['Dryness', 'Sensitivity', 'Dull Skin', 'Mild Acne'],
    description: 'A gentle night cream formulated with hydrosols, botanical extracts and vitamins to calm, hydrate and repair skin overnight, leaving it soft, smooth and radiant.',
    storyTitle: 'Overnight Botanical Restoration',
    storyText: 'While you sleep, a potent blend of Rose Hydrosol, Squalane and Niacinamide works to calm irritation, deeply hydrate and repair your skin’s natural barrier. Wake up to visibly softer, renewed skin.',
    stats: [
      { value: '96%', label: 'DEEPER HYDRATION' },
      { value: '94%', label: 'SOFTER SKIN' },
      { value: '98%', label: 'CALMER COMPLEXION' },
    ],
    featuredIngredients: [
      { name: 'Squalane', desc: 'A luxurious plant-derived oil identical to skin’s own moisture. Deeply nourishes without clogging pores.' },
      { name: 'Niacinamide', desc: 'Vitamin B3 that strengthens the skin barrier, reduces redness and improves overall skin texture and tone.' },
      { name: 'Rose Hydrosol', desc: 'The essence of Bulgarian roses. Calms inflammation, balances pH and envelops skin in gentle hydration.' },
    ],
    allIngredients: ['Rose Hydrosol', 'Aloe Vera', 'Squalane', 'Jojoba Oil', 'Licorice Extract', 'Gotu Kola', 'Niacinamide', 'Chamomile', 'Panthenol', 'Vitamin E'],
    texture: 'Lightweight, Creamy, Non-greasy',
    fragrance: 'Mild hypoallergenic fragrance',
    howToUse: 'Apply a small amount on clean face at night and massage gently until absorbed.',
    whenToUse: 'Night / Daily',
    suitableFor: ['Normal Skin', 'Dry Skin', 'Sensitive Skin', 'Acne-prone Skin'],
    claims: ['Low Irritation', 'Acne Safe', 'Alcohol Free', 'Retinol Free', 'Gentle Botanical Formula'],
    shelfLife: '24 Months',
    storage: 'Store in a cool & dry place away from direct sunlight.',
    safety: 'For external use only. Avoid contact with eyes. Patch test recommended.',
    reviews: [
      { text: 'Gentle and soothing for sensitive skin. I wake up feeling truly refreshed and renewed.', author: 'Nisha D.', rating: 5 },
      { text: 'Deep hydration with soft glow. My skin has never been this calm overnight.', author: 'Pooja V.', rating: 5 },
      { text: 'Lightweight and non-greasy formula that actually works. My acne hasn’t flared up since!', author: 'Shruti L.', rating: 5 },
    ],
    storyImage: '',
  },
  {
    id: 'hairoil',
    name: 'ULTRA SENSITIVE HAIR GROWTH ELIXIR HAIR OIL',
    shortName: 'HAIR OIL',
    displayName: 'Hair Growth Elixir',
    subtitle: 'Ultra Sensitive Care',
    category: 'hair',
    tagline: 'Gentle Herbal Care • Hair Growth Support • Scalp Nourishment',
    price: 299,
    priceDisplay: '₹299.00',
    size: '100 ML',
    sizeDetail: '100 ml (3.38 fl oz)',
    rating: 4.7,
    image: '',
    themeColor: '#C9A227',
    themeBg: '#FDFBF7',
    themeGradient: ['#FDFBF7', '#F6F0DF'] as [string, string],
    highlights: [
      { icon: 'leaf', label: 'Female scalp care herbal oil blend' },
      { icon: 'droplets', label: 'Lightweight & non-sticky' },
      { icon: 'sparkles', label: 'Vitamins & conditioning actives' },
    ],
    benefits: [
      'Helps support healthy hair growth',
      'Nourishes and strengthens hair roots',
      'Improves scalp health and hydration',
      'Helps reduce dryness and hair fall',
      'Makes hair softer, smoother and shinier',
    ],
    concerns: ['Hair Fall', 'Weak Roots', 'Dry Scalp', 'Slow Hair Growth'],
    description: 'A gentle herbal hair oil formulated with nourishing carrier oils, botanical extracts and scalp-conditioning actives to support healthy hair growth, strengthen roots and maintain a balanced scalp environment.',
    storyTitle: 'The Root Ritual',
    storyText: 'A lightweight infusion that deeply nourishes the scalp without feeling tacky. Designed exclusively for sensitive, dry profiles experiencing weak roots.',
    stats: [
      { value: '96%', label: 'STRONGER ROOTS' },
      { value: '92%', label: 'LESS HAIR FALL' },
      { value: '98%', label: 'SCALP HYDRATION' },
    ],
    featuredIngredients: [
      { name: 'Bhringraj & Amla', desc: 'Renowned Ayurvedic herbs that actively stimulate follicles and support robust hair growth.' },
      { name: 'Sugarcane Squalane', desc: 'A deeply hydrating, weightless active that smooths hair cuticles and provides brilliant shine.' },
      { name: 'Caffeine', desc: 'Energizes the scalp ecosystem and offsets factors that lead to thinning.' },
    ],
    allIngredients: ['Coconut MCT Oil', 'Black Sesame Oil', 'Jojoba Oil', 'Argan Oil', 'Castor Oil', 'Bhringraj Extract', 'Amla Extract', 'Fenugreek Extract', 'Hibiscus Extract', 'Brahmi Extract', 'Gotu Kola Extract', 'Sugarcane Squalane', 'Vitamin E', 'Caffeine'],
    texture: 'Lightweight, Smooth, Non-sticky Oil',
    fragrance: 'Mild Herbal Aroma with Natural Essential Oils',
    howToUse: 'Take a small amount of oil and gently massage onto scalp and hair roots. Leave for a few hours or overnight before washing with a mild shampoo.',
    whenToUse: '2–3 times a week or as needed',
    suitableFor: ['Normal', 'Dry', 'Weak & Sensitive Scalp Hair Types'],
    claims: ['Preservative Free', 'Silicone Free', 'Mineral Oil Free', 'Gentle Herbal Formula'],
    shelfLife: '24 Months',
    brand: 'D A LUXE',
    madeIn: 'India',
    reviews: [
      { text: 'Nourishes scalp and strengthens hair roots!', author: 'Sneha R.', rating: 5 },
      { text: 'Lightweight and non-greasy oil, I can leave it on overnight comfortably.', author: 'Riya K.', rating: 5 },
      { text: 'Suitable for regular scalp massage, saw baby hairs coming in.', author: 'Aarti M.', rating: 4.5 },
    ],
  },
  {
    id: 'hairshampoo',
    name: 'ULTRA SENSITIVE CALM & CLEAN HAIR SHAMPOO',
    shortName: 'SHAMPOO',
    displayName: 'Calm & Clean Shampoo',
    subtitle: 'Ultra Sensitive Care',
    category: 'hair',
    tagline: 'Gentle Herbal Cleanse • No-Itch Comfort • Sensitive Scalp Care',
    price: 249,
    priceDisplay: '₹249.00',
    size: '100 ML',
    sizeDetail: '100 ml (3.38 fl oz)',
    rating: 4.7,
    image: '',
    themeColor: '#7A918D',
    themeBg: '#F2F5F4',
    themeGradient: ['#F2F5F4', '#E8ECEB'] as [string, string],
    highlights: [
      { icon: 'droplets', label: 'Reduced saponin blend for gentle washing' },
      { icon: 'leaf', label: 'Anti-itch soothing botanical extracts' },
      { icon: 'sparkles', label: 'Lightweight conditioning for soft hair' },
    ],
    benefits: [
      'Gently cleanses hair without irritation',
      'Helps soothe itchy and sensitive scalp',
      'Maintains scalp hydration and balance',
      'Leaves hair soft, smooth and manageable',
      'Suitable for regular gentle cleansing',
    ],
    concerns: ['Sensitive Scalp', 'Itching', 'Dryness', 'Mild Irritation'],
    description: 'A mild herbal shampoo specially designed for sensitive female scalp. Enriched with botanical extracts and soothing actives that gently cleanse hair while helping reduce scalp irritation and dryness.',
    storyTitle: 'The Pure Cleanse',
    storyText: 'A sulfate-free, deeply soothing rinse that respects the sensitive barrier of your scalp, eliminating itch without stripping away essential moisture.',
    stats: [
      { value: '97%', label: 'ITCH RELIEF' },
      { value: '95%', label: 'SCALP COMFORT' },
      { value: '94%', label: 'SOFTER HAIR' },
    ],
    featuredIngredients: [
      { name: 'Reetha & Shikakai', desc: 'Natural saponins that provide a mild, non-stripping cleanse perfect for delicate barriers.' },
      { name: 'Aloe Vera & Allantoin', desc: 'Super-soothing complexes that instantly calm irritation, redness, and itching.' },
      { name: 'Panthenol (Vitamin B5)', desc: 'Penetrates the hair shaft to lock in intense moisture and boost elasticity.' },
    ],
    allIngredients: ['Reetha Extract', 'Shikakai Extract', 'Amla Extract', 'Aloe Vera Extract', 'Licorice Extract', 'Neem Extract', 'Fenugreek Extract', 'Hibiscus Extract', 'Bhringraj Extract', 'Virgin Coconut Oil', 'Castor Oil', 'Panthenol (Vitamin B5)', 'Allantoin', 'Vitamin E'],
    texture: 'Lightweight Liquid Shampoo, Smooth Foam',
    fragrance: 'Mild Herbal Fragrance',
    howToUse: 'Apply a small amount of shampoo on wet hair. Massage gently into scalp and hair. Rinse thoroughly with water.',
    whenToUse: '2–3 times per week or as needed',
    suitableFor: ['Sensitive', 'Dry', 'Itchy & Normal Scalp'],
    claims: ['Paraben Free', 'Silicone Free', 'Gentle Herbal Formula', 'Suitable for Sensitive Scalp'],
    shelfLife: '24 Months',
    brand: 'D A LUXE',
    madeIn: 'India',
    reviews: [
      { text: 'Gentle cleansing without irritation, finally a shampoo that works.', author: 'Kriti S.', rating: 5 },
      { text: 'Soothes my itchy scalp perfectly, highly recommend!', author: 'Priyanka D.', rating: 4.5 },
      { text: 'Leaves hair soft and manageable all day long.', author: 'Meera T.', rating: 5 },
    ],
  },
  {
    id: 'skin-combo',
    name: 'VIRGIN 5.0 SKINCARE COMBO',
    shortName: 'SKIN COMBO',
    displayName: 'Virgin 5.0 Skincare Combo',
    subtitle: 'Complete Skin Repair & Glow Solution',
    category: 'combo',
    tagline: 'Cleanse, Repair & Glow with Gold Glow Ritual',
    price: 1097,
    priceDisplay: '₹1,097.00',
    mrp: '₹1,147',
    size: 'COMBO PACK',
    sizeDetail: 'Facewash + Face Serum + Night Cream + FREE Facewash',
    rating: 4.8,
    image: '',
    themeColor: '#C9A84C',
    themeBg: '#FDFBF0',
    themeGradient: ['#FDFBF0', '#FAF3E0'] as [string, string],
    highlights: [
      { icon: 'gift', label: 'FREE 50ml Facewash included' },
      { icon: 'leaf', label: 'Dermal-grade botanical formula' },
      { icon: 'sparkles', label: 'Complete 3-step repair routine' },
    ],
    benefits: [
      'Deeply cleans dirt, oil & impurities',
      'Helps reduce acne, pimples & marks',
      'Boosts natural glow & brightness',
      'Overnight skin repair & barrier support',
    ],
    concerns: ['Acne Marks', 'Dullness', 'Uneven Texture', 'Sensitivity'],
    description: 'A complete 3-step skincare transformation routine. Features our Gold Glow Facewash, Repair Serum, and Night Cream to cleanse, nourish and restore your skin naturally.',
    storyTitle: 'The Complete Skin Ritual',
    storyText: 'Expertly curated for sensitive skin, this combo integrates our core dermal-grade products to deliver a holistic repair experience. From the first cleanse to overnight restoration, your skin stays protected and radiant.',
    stats: [
      { value: '100%', label: 'SENSITIVE SAFE' },
      { value: '98%', label: 'GLOW BOOST' },
      { value: '95%', label: 'REPAIR RATE' },
    ],
    featuredIngredients: [
      { name: '24K Gold & Saffron', desc: 'Luxurious brightening actives for an instant luminous glow.' },
      { name: 'Niacinamide & Squalane', desc: 'Potent barrier repair duo that calms and hydrates deeply.' },
      { name: 'Rose Hydrosol', desc: 'Calming botanical base that balances pH and soothes redness.' },
    ],
    allIngredients: ['Rose Hydrosol', '24K Gold Leaf', 'Saffron', 'Squalane', 'Niacinamide', 'Aloe Vera', 'Vitamin C', 'Hyaluronic Acid'],
    texture: 'Complete 3-step texture set (Gel, Serum, Cream)',
    fragrance: 'Mild botanical wellness aroma',
    howToUse: 'Step 1: Cleanse with Facewash. Step 2: Apply Face Serum. Step 3: Apply Night Cream.',
    whenToUse: 'Daily (AM & PM)',
    suitableFor: ['All Skin Types', 'Sensitive Skin'],
    claims: ['Chemical Free', 'Dermal Grade', 'Acne Safe', 'Eco-Conscious Packaging'],
    shelfLife: '24 Months',
    // Combo-specific detail fields (used by ComboDetailPage)
    tag: 'SKINCARE COMBO',
    freeBadge: 'FREE 50ml Facewash with every order',
    includes: [
      { name: 'Ultra Sensitive Gold Glow Facewash', size: '100 ml' },
      { name: 'Ultra Sensitive Face Serum', size: '30 ml' },
      { name: 'Ultra Sensitive Repair Night Cream', size: '30 g' },
      { name: 'Bonus Facewash', size: '50 ml FREE' },
    ],
    ingredients: ['Aloe Vera', 'Vitamin C', 'Hyaluronic Acid', 'Niacinamide', 'Herbal Extracts', 'Gold Glow Infusion'],
    routine: [
      { time: 'Morning', steps: ['Use Facewash — Cleanse your face', 'Apply Face Serum — For glow & hydration'] },
      { time: 'Night', steps: ['Wash face with Facewash', 'Apply Face Serum', 'Apply Night Cream — Overnight repair'] },
    ],
    tags: ['Sensitive Skin Safe', 'Dermal-Grade', 'Chemical-Free', 'Daily Use'],
    reviews: [
      { text: 'The best combo for my sensitive skin. The glow is real!', author: 'Anjali R.', rating: 5 },
      { text: 'Great value for money and the products actually work together perfectly.', author: 'Vikram S.', rating: 5 },
    ],
  },
  {
    id: 'hair-combo',
    name: 'VIRGIN 5.0 HAIR CARE COMBO',
    shortName: 'HAIR COMBO',
    displayName: 'Virgin 5.0 Hair Care Combo',
    subtitle: 'Complete Hair Repair & Growth Solution',
    category: 'combo',
    tagline: 'Reduce Fall, Boost Growth & Add Shine',
    price: 897,
    priceDisplay: '₹897.00',
    mrp: '₹1,147',
    size: 'COMBO PACK',
    sizeDetail: 'Hair Oil + Shampoo + Hair Serum + FREE Shampoo',
    rating: 4.7,
    image: '',
    themeColor: '#7B9E6B',
    themeBg: '#F5FAF0',
    themeGradient: ['#F5FAF0', '#EFF6E8'] as [string, string],
    highlights: [
      { icon: 'gift', label: 'FREE 50ml Shampoo included' },
      { icon: 'leaf', label: 'Pure botanical growth elixir' },
      { icon: 'sparkles', label: 'Visible thickness & volume boost' },
    ],
    benefits: [
      'Significantly reduces hair fall',
      'Promotes visible hair growth',
      'Controls frizz & adds mirror-shine',
      'Nourishes itchy & dry scalp',
    ],
    concerns: ['Hair Fall', 'Thinning', 'Dryness', 'Itchy Scalp'],
    description: 'A botanical hair transformation system. Combines our growth elixir oil, calm & clean shampoo, and smooth & shine serum for a complete root-to-tip care routine.',
    storyTitle: 'The Growth Philosophy',
    storyText: 'By treating the scalp and hair as a single ecosystem, our hair combo addresses the root causes of fall while enhancing the lifespan of each strand. No silicones, just botanical strength.',
    stats: [
      { value: '97%', label: 'LESS FALL' },
      { value: '94%', label: 'MORE SHINE' },
      { value: '92%', label: 'GROWTH BOOST' },
    ],
    featuredIngredients: [
      { name: 'Bhringraj Oil', desc: 'The king of herbs for hair growth and scalp nourishment.' },
      { name: 'Argan & Jojoba', desc: 'Lightweight oils that seal moisture and add weightless shine.' },
      { name: 'Reetha & Shikakai', desc: 'Natural cleansers that respect the scalp barrier.' },
    ],
    allIngredients: ['Argan Oil', 'Bhringraj', 'Shikakai', 'Reetha', 'Coconut MCT', 'Jojoba', 'Hibiscus', 'Amla'],
    texture: 'Complete hair system (Oil, Liquid Cleanser, Serum)',
    fragrance: 'Refreshing herbal forest aroma',
    howToUse: '1. Massage Oil into scalp. 2. Wash with Shampoo. 3. Apply Serum to lengths.',
    whenToUse: '2-3 times/week (Oil & Shampoo), Daily (Serum)',
    suitableFor: ['All Hair Types', 'Sensitive Scalp'],
    claims: ['Silicone Free', 'Sulphate Free', 'Botanical actives', 'Cruelty Free'],
    shelfLife: '24 Months',
    // Combo-specific detail fields (used by ComboDetailPage)
    tag: 'HAIR CARE COMBO',
    freeBadge: 'FREE 50ml Shampoo with every order',
    includes: [
      { name: 'Hair Growth Elixir Oil', size: '100 ml' },
      { name: 'Ultra Sensitive Calm & Clean Shampoo', size: '100 ml' },
      { name: 'Smooth & Shine Hair Serum', size: '30 ml' },
      { name: 'Bonus Shampoo', size: '50 ml FREE' },
    ],
    ingredients: ['Coconut Oil', 'Black Sesame Oil', 'Argan Oil', 'Bhringraj Extract', 'Amla Extract', 'Aloe Vera', 'Hibiscus Extract'],
    routine: [
      { time: 'Step 1 — Oil', steps: ['Apply oil on scalp, massage 5–10 mins', 'Leave overnight for best results'] },
      { time: 'Step 2 — Shampoo', steps: ['Wash hair with a small amount', 'Gently cleanse scalp and rinse'] },
      { time: 'Step 3 — Serum', steps: ['Apply a few drops on dry or damp hair', 'Style as desired'] },
    ],
    tags: ['Sensitive Scalp Safe', 'Botanical Formula', 'Chemical-Free', 'All Hair Types'],
    reviews: [
      { text: 'My hair fall stopped after just 2 weeks of using this combo.', author: 'Priya K.', rating: 5 },
      { text: 'Finally a hair system that doesnt irritate my scalp.', author: 'Rohit M.', rating: 4.5 },
    ],
  },
];
